apiVersion: apps/v1
kind: Deployment
metadata:
  name: hera-app
  namespace: hera-namespace
  labels:
    app: hera-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hera-app
  template:
    metadata:
      labels:
        app: hera-app
    spec:
      containers:
      - name: hera-app-container
        image: prod-mione-opensource-registry.cn-beijing.cr.aliyuncs.com/prod-mione-opensource/prod-mione-opensource:hera-app-v9
        resources:
          limits:
            cpu: '300m'
            memory: 1Gi
